video_generator:
  fps: 6

tortoise_tts:
  audio_sampling_rate: 24000
  default_voice: "train_empire"
  voice_actors : ["train_empire","train_atkins", "train_dreams", "train_lescault", "train_kennard", "train_grace"]
  # voice_actors: ["train_empire","train_atkins", "train_dreams", "train_lescault", "train_kennard", "train_grace", "train_dotrice"]

vits:
  audio_sampling_rate: 22050
  # Change below to name of models
  voice_actors: ["pretrained_vctk"]

models:
  # sd: "stabilityai/stable-diffusion-2-1-base"
  sd: "nightvisionXLPhotorealisticPortrait_v0791Bakedvae.safetensors"
  svd: "svd_xt"
  # svd: "svd"